application: cruzalinhas
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /rebuild
  script: frontend.py
  login: admin

- url: /load
  script: bulkloader.py
  login: admin

- url: /.*
  script: frontend.py


