application: cruzalinhas
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /clearcache
  script: frontend.py
  login: admin
    
- url: /zap
  script: frontend.py
  login: admin
    
- url: /load-linha
  script: linhaloader.py
  login: admin

- url: /load-ponto
  script: pontoloader.py
  login: admin

- url: /.*
  script: frontend.py


