application: cruzalinhas
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /zap
  script: frontend.py
  login: admin

#- url: /remote_api
#  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#  login: admin

- url: /load
  script: pontoloader.py
  login: admin

- url: /.*
  script: frontend.py


